/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package namecalculator;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JOptionPane;
import myframework.pkgDataBase.ClsHSQLDBDataBase;
import myframework.pkgGUIContainers.ClsGUIContainers;

/**
 *
 * @author Windows2K
 */
public class FrmMain extends javax.swing.JFrame {

    public ClsHSQLDBDataBase objDBHSQ;
    ClsGUIContainers objGUIContainer;
    DlgLogin objDlg;
    IntrnlFrmChooseNames objChooseNames;
    IntrnlFrmFormatNames objFormatNames;

    public FrmMain() {
        initComponents();
        objDBHSQ = ClsHSQLDBDataBase.self(txtLogs);
        objGUIContainer = ClsGUIContainers.self(txtLogs);
        objDlg = DlgLogin.self(this, true);
    }

    static FrmMain objFrm;

    public static FrmMain self() {
        if (objFrm == null) {
            objFrm = new FrmMain();
        }
        return objFrm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu2 = new javax.swing.JMenu();
        mnuCopyNamesFromWebsite1 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuChooseNames1 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuClearLog1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuExit1 = new javax.swing.JMenuItem();
        scrmain = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogs = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCopyNamesFromWebsite = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuChooseNames = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuClearLog = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();

        jMenu2.setText("Action");

        mnuCopyNamesFromWebsite1.setText("Copy Names From Website");
        mnuCopyNamesFromWebsite1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCopyNamesFromWebsite1ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCopyNamesFromWebsite1);
        jMenu2.add(jSeparator5);

        mnuChooseNames1.setText("Choose Names");
        mnuChooseNames1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChooseNames1ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuChooseNames1);
        jMenu2.add(jSeparator6);

        mnuClearLog1.setText("Clear Log");
        mnuClearLog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClearLog1ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuClearLog1);
        jMenu2.add(jSeparator3);

        mnuExit1.setText("Exit");
        mnuExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExit1ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuExit1);

        jPopupMenu1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Choose Your Baby Name");
        setState(2);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        scrmain.setBackground(new java.awt.Color(255, 255, 51));
        scrmain.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrmain.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jDesktopPane1.setBackground(new java.awt.Color(255, 153, 255));
        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDesktopPane1MouseReleased(evt);
            }
        });
        jDesktopPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jDesktopPane1ComponentResized(evt);
            }
        });

        txtLogs.setEditable(false);
        txtLogs.setColumns(20);
        txtLogs.setRows(5);
        jScrollPane1.setViewportView(txtLogs);

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        scrmain.setViewportView(jDesktopPane1);

        getContentPane().add(scrmain, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Action");

        mnuCopyNamesFromWebsite.setText("Copy Names From Website");
        mnuCopyNamesFromWebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCopyNamesFromWebsiteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCopyNamesFromWebsite);
        jMenu1.add(jSeparator2);

        mnuChooseNames.setText("Choose Names");
        mnuChooseNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChooseNamesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuChooseNames);
        jMenu1.add(jSeparator4);

        mnuClearLog.setText("Clear Log");
        mnuClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClearLogActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClearLog);
        jMenu1.add(jSeparator1);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCopyNamesFromWebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCopyNamesFromWebsiteActionPerformed
        // TODO add your handling code here:
        fnCopyNamesFromWebsiteActionPerformed();
    }//GEN-LAST:event_mnuCopyNamesFromWebsiteActionPerformed

    private void jDesktopPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane1MouseReleased
        // TODO add your handling code here:
        if (evt.getButton() == 3) {
            jPopupMenu1.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jDesktopPane1MouseReleased

    private void mnuChooseNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChooseNamesActionPerformed
        // TODO add your handling code here:
        fnChooseNames();
    }//GEN-LAST:event_mnuChooseNamesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (objGUIContainer.fnShowConfirmDialog(this, "Do you want to close the application?", "Information", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            try {
                objDBHSQ.fnCloseDb("ChooseYourBabyName");
            } catch (SQLException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            objDlg.setVisible(true);

            String strDBPath = "";

            if (System.getProperty("os.name").equals("Linux")) {
                strDBPath = new File(".").getCanonicalPath() + "/resource/babynames.db";
            } else {
                strDBPath = new File(".").getCanonicalPath() + "\\resource\\babynames.db";
            }
            try {
                objDBHSQ.fnConnectDB("ChooseYourBabyName","", 0, "", "", strDBPath, objDlg.txtUserName.getText(), objDlg.txtPassword.getText());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            objDlg.dispose();
            objDlg = null;
        } catch (IOException ex) {
            objGUIContainer.fnShowConfirmDialog(this, ex.getMessage(), "Information", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jDesktopPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDesktopPane1ComponentResized
        // TODO add your handling code here:

    }//GEN-LAST:event_jDesktopPane1ComponentResized

    private void mnuClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClearLogActionPerformed
        // TODO add your handling code here:
        txtLogs.setText("");
    }//GEN-LAST:event_mnuClearLogActionPerformed

    private void mnuCopyNamesFromWebsite1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCopyNamesFromWebsite1ActionPerformed
        // TODO add your handling code here:
        mnuCopyNamesFromWebsiteActionPerformed(evt);
    }//GEN-LAST:event_mnuCopyNamesFromWebsite1ActionPerformed

    private void mnuChooseNames1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChooseNames1ActionPerformed
        // TODO add your handling code here:
        mnuChooseNamesActionPerformed(evt);
    }//GEN-LAST:event_mnuChooseNames1ActionPerformed

    private void mnuClearLog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClearLog1ActionPerformed
        // TODO add your handling code here:
        mnuClearLogActionPerformed(evt);
    }//GEN-LAST:event_mnuClearLog1ActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExit1ActionPerformed
        // TODO add your handling code here:
        mnuExitActionPerformed(evt);
    }//GEN-LAST:event_mnuExit1ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        this.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        scrmain.setPreferredSize(this.getPreferredSize());
        Dimension objD = scrmain.getPreferredSize();
        objD.height = objD.height + (objD.height / 8);

        jDesktopPane1.setPreferredSize(objD);

        if (objGUIContainer != null) {
            objGUIContainer.fnShowInternalFormMiddle(this.jDesktopPane1, objDlg, false);
        }
    }//GEN-LAST:event_formComponentResized

    private void fnChooseNames() {
        objChooseNames = IntrnlFrmChooseNames.self();
        objGUIContainer.fnShowInternalFormCenter(objChooseNames, FrmMain.self().jDesktopPane1, true);

    }

    private void fnCopyNamesFromWebsiteActionPerformed() {

        objFormatNames = IntrnlFrmFormatNames.self();
        objGUIContainer.fnShowInternalFormCenter(objFormatNames, FrmMain.self().jDesktopPane1, true);

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem mnuChooseNames;
    private javax.swing.JMenuItem mnuChooseNames1;
    private javax.swing.JMenuItem mnuClearLog;
    private javax.swing.JMenuItem mnuClearLog1;
    private javax.swing.JMenuItem mnuCopyNamesFromWebsite;
    private javax.swing.JMenuItem mnuCopyNamesFromWebsite1;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuExit1;
    private javax.swing.JScrollPane scrmain;
    public javax.swing.JTextArea txtLogs;
    // End of variables declaration//GEN-END:variables
}
